export const TOP_LEVEL_FIELDS = new Set([
  "$schema",
  "log",
  "dns",
  "ntp",
  "certificate",
  "endpoints",
  "inbounds",
  "outbounds",
  "route",
  "services",
  "experimental",
]);

export const OUTBOUND_TYPES = new Set([
  "direct",
  "block",
  "socks",
  "http",
  "shadowsocks",
  "vmess",
  "trojan",
  "hysteria",
  "vless",
  "shadowtls",
  "tuic",
  "hysteria2",
  "anytls",
  "ssh",
  "selector",
  "urltest",
  "naive",
]);

export const ENDPOINT_TYPES = new Set(["wireguard", "tailscale"]);

export const RULE_CONDITION_FIELDS = new Set([
  "inbound",
  "ip_version",
  "network",
  "auth_user",
  "protocol",
  "client",
  "domain",
  "domain_suffix",
  "domain_keyword",
  "domain_regex",
  "geosite",
  "source_geoip",
  "geoip",
  "source_ip_cidr",
  "source_ip_is_private",
  "ip_cidr",
  "ip_is_private",
  "source_port",
  "source_port_range",
  "port",
  "port_range",
  "process_name",
  "process_path",
  "process_path_regex",
  "package_name",
  "user",
  "user_id",
  "clash_mode",
  "network_type",
  "network_is_expensive",
  "network_is_constrained",
  "interface_address",
  "network_interface_address",
  "default_interface_address",
  "wifi_ssid",
  "wifi_bssid",
  "preferred_by",
  "rule_set",
  "rule_set_ip_cidr_match_source",
  "rule_set_ipcidr_match_source",
  "invert",
]);

export const RULE_ACTION_FIELDS = new Set([
  "action",
  "outbound",
  "override_address",
  "override_port",
  "network_strategy",
  "fallback_delay",
  "udp_disable_domain_unmapping",
  "udp_connect",
  "udp_timeout",
  "tls_fragment",
  "tls_fragment_fallback_delay",
  "tls_record_fragment",
]);

export const LOGICAL_RULE_FIELDS = new Set([
  "type",
  "mode",
  "rules",
  "invert",
  ...RULE_ACTION_FIELDS,
]);

export const DEFAULT_RULE_FIELDS = new Set([
  "type",
  ...RULE_CONDITION_FIELDS,
  ...RULE_ACTION_FIELDS,
]);
